name: Build flatpak package (latest)

on:  workflow_dispatch

env:
  APP_NAME:    alsa-scarlett-gui

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Build flatpak package
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ${{ env.APP_NAME }}.flatpak
        manifest-path: vu.b4.alsa-scarlett-gui.yml
        cache-key: flatpak-builder-${{ github.sha }}
